# Generated by Django 4.2.30 on 2026-06-19 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solvecenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HardwareDevices',
            new_name='Hardware',
        ),
        migrations.RenameModel(
            old_name='SoftwareProducts',
            new_name='Software',
        ),
        migrations.AlterModelOptions(
            name='hardware',
            options={'ordering': ['hardware_devices'], 'verbose_name_plural': 'Hardware'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['software_products'], 'verbose_name_plural': 'Software'},
        ),
        migrations.RenameField(
            model_name='hardware',
            old_name='hardware',
            new_name='hardware_devices',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='software',
            new_name='software_products',
        ),
    ]
