# Generated by Django 6.0.6 on 2026-07-01 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvecenter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolution',
            name='id',
        ),
        migrations.AlterField(
            model_name='resolution',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resolutions', serialize=False, to='solvecenter.issue'),
        ),
    ]
