# Generated by Django 4.2.30 on 2026-06-20 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solvecenter', '0002_rename_hardwaredevices_hardware_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardware',
            options={'ordering': ['hardware_device'], 'verbose_name_plural': 'Hardware'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['software_product'], 'verbose_name_plural': 'Software'},
        ),
        migrations.RenameField(
            model_name='hardware',
            old_name='hardware_devices',
            new_name='hardware_device',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='software_products',
            new_name='software_product',
        ),
    ]
