# Generated by Django 6.0.6 on 2026-06-23 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvecenter', '0003_alter_hardware_options_alter_software_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='hardware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solvecenter.hardware'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solvecenter.software'),
        ),
    ]
