# Generated by Django 6.0.6 on 2026-06-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvecenter', '0004_alter_issue_hardware_alter_issue_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='reported_resolution',
            field=models.TextField(blank=True, default=''),
        ),
    ]
