# Generated by Django 6.0.6 on 2026-06-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvecenter', '0005_alter_resolution_reported_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='reported_resolution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
